---
# tasks file for roles/prometheus
- name: Add Prometheus configuration template
  template:
    src: prometheus.yml.j2
    dest: /tmp/prometheus.yml

- name: Create Prometheus container
  docker_container:
    name: "{{ container_name }}"
    image: prom/prometheus:latest
    networks:
      - name: "{{ network }}"
    recreate: yes
    ports:
      - "{{ container_port }}: 9090"
    restart: yes
    volumes:
      - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
    restart_policy: "{{ restart_policy }}"
    purge_networks: yes
    networks_cli_compatible: yes