---
# tasks file for roles/grafana
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - software-properties-common

- name: Install Grafana GPG key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key

- name: Add Grafana repository
  lineinfile:
    path: /etc/apt/sources.list.d/grafana.list
    create: yes
    line: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present

- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Add Grafana dashboard JSON file
  copy:
    src: node-exporter-full.json
    dest: /var/lib/grafana/dashboards/
    mode: 0755

- name: Add Grafana dashboard configuration file
  copy:
    src: node-exporter-full.yaml
    dest: /etc/grafana/provisioning/dashboards/node-exporter-full.yaml
  notify: restart grafana

- name: Add Prometheus datasource configuration file
  template:
    src: prometheus.yaml.j2
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
  notify: restart grafana

- name: Start Grafana service
  service:
    name: grafana-server
    state: started

- name: Enable Grafana service
  service:
    name: grafana-server
    enabled: yes