- hosts: Docker
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - cloud-utils
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ lsb_release }} stable
        state: present

    - name: Install Docker package
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Add the user to the group
      user:
        name: ubuntu
        shell: /bin/bash
        groups: docker
        append: yes
