FROM ubuntu:latest

LABEL maintainer="Tania Arutiunian" name="Grafana"

WORKDIR /grafana

RUN apt-get update && \
    apt-get install -y apt-transport-https software-properties-common wget && \
    wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key && \
    echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | tee -a /etc/apt/sources.list.d/grafana.list && \
    apt-get update && \
    apt-get install -y grafana

EXPOSE 3000

ENTRYPOINT ["grafana-server"]

CMD ["--homepath=/usr/share/grafana"]
