FROM ubuntu

LABEL maintainer="Tania Arutiunian" name="Node Exporter"

WORKDIR /node-exporter

ADD https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz .

RUN tar xvfz node_exporter-*.tar.gz && \
    mv node_exporter-1.5.0.linux-amd64/node_exporter /usr/local/bin && \
    rm -r node_exporter-1.5.0.linux-amd64*

EXPOSE 9100

ENTRYPOINT ["/usr/local/bin/node_exporter"]