FROM ubuntu

LABEL maintainer="Tania Arutiunian <tanyaharutyunyan01@gmail.com>"

WORKDIR /grafana

RUN apt-get update && \
    apt-get install -y apt-transport-https software-properties-common wget && \
    wget -q -O /usr/share/keyrings/grafana.key https://apt.grafana.com/gpg.key && \
    echo "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main" | tee -a /etc/apt/sources.list.d/grafana.list && \
    apt-get update && \
    apt-get install -y grafana

EXPOSE 3000

ENTRYPOINT ["grafana-server"]

CMD ["--config=/etc/grafana/grafana.ini", "--homepath=/usr/share/grafana"]
